# Generated by Django 3.0.2 on 2020-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_address', models.CharField(max_length=255)),
                ('cust_phone', models.CharField(max_length=255)),
                ('cust_type', models.CharField(max_length=255)),
                ('cust_id', models.CharField(max_length=255, unique=True)),
                ('cust_since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_type', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
