# Generated by Django 3.0.4 on 2020-03-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='cust_type',
            field=models.CharField(max_length=255),
        ),
    ]
