# Generated by Django 3.0.4 on 2020-03-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0002_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=255)),
                ('ad_id', models.IntegerField(unique=True)),
                ('price', models.FloatField()),
                ('gst', models.FloatField()),
                ('total', models.FloatField()),
                ('billing_date', models.DateField()),
                ('bill_status', models.CharField(default='unpaid', max_length=255)),
            ],
        ),
    ]
