# Generated by Django 3.0.4 on 2020-03-24 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0003_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejected',
            name='rej_date',
            field=models.DateField(default=datetime.date(2020, 3, 24)),
        ),
    ]
