# Generated by Django 3.0.4 on 2020-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0003_auto_20200312_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prices',
            name='cust_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
