# Generated by Django 3.0.4 on 2020-03-24 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0004_rejected_rej_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejected',
            name='rej_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
