# Generated by Django 3.0.2 on 2020-03-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0006_auto_20200312_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_phone',
        ),
    ]
