# Generated by Django 3.0.4 on 2020-03-24 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0006_auto_20200324_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=255)),
                ('ad_id', models.CharField(max_length=255)),
                ('bill_id', models.IntegerField()),
                ('payment_due', models.FloatField()),
                ('payment_amount', models.FloatField()),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 8, 48, 332612, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='rejected',
            name='rej_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 8, 48, 159602, tzinfo=utc)),
        ),
    ]
