# Generated by Django 3.0.4 on 2020-03-24 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0008_auto_20200324_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 9, 54, 843416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='rej_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 9, 54, 592401, tzinfo=utc)),
        ),
    ]
