# Generated by Django 3.0.2 on 2020-03-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0008_auto_20200313_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_address',
        ),
    ]
