# Generated by Django 3.0.2 on 2020-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0009_remove_customer_cust_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
