# Generated by Django 3.0.4 on 2020-03-24 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainActivity', '0009_auto_20200324_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 15, 32, 47, 734757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='rej_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 15, 32, 47, 558747, tzinfo=utc)),
        ),
    ]
